project:
  type: website
  output-dir: docs
  render:
  - index.qmd
  - 03_data_analysis.qmd
  - 04_results.qmd
  - slides.qmd   # keep if you use it
  - hello.qmd

jupyter: python3

website:
  title: "FinBERT vs VADER"
  navbar:
    left:
      - file: index.qmd
      - file: 03_data_analysis.qmd
      - file: 04_results.qmd
      - file: slides.qmd
      - file: hello.qmd

format:
  html:
    theme: cosmo

execute:
  echo: true
  warning: false
